"""Initial migration with user table

Revision ID: cccc58c0b3ce
Revises: 
Create Date: 2025-12-23 23:37:55.895976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cccc58c0b3ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ab_user',
    sa.Column('id', sa.Integer(), nullable=False, comment='用户唯一ID'),
    sa.Column('email', sa.String(), nullable=False, comment='用户邮箱，唯一且非空，作为登录凭证'),
    sa.Column('phone_number', sa.String(), nullable=True, comment='用户手机号，可选，唯一'),
    sa.Column('name', sa.String(), nullable=True, comment='用户名称，可选'),
    sa.Column('hashed_password', sa.String(), nullable=False, comment='用户密码的哈希值'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='用户账户是否活跃状态'),
    sa.Column('login_count', sa.Integer(), nullable=False, comment='用户登录次数'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='用户上次登录时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='用户创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='用户最后更新时间'),
    sa.Column('bio', sa.Text(), nullable=True, comment='用户个人介绍或简介'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ab_user_email'), 'ab_user', ['email'], unique=True)
    op.create_index(op.f('ix_ab_user_id'), 'ab_user', ['id'], unique=False)
    op.create_index(op.f('ix_ab_user_name'), 'ab_user', ['name'], unique=False)
    op.create_index(op.f('ix_ab_user_phone_number'), 'ab_user', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ab_user_phone_number'), table_name='ab_user')
    op.drop_index(op.f('ix_ab_user_name'), table_name='ab_user')
    op.drop_index(op.f('ix_ab_user_id'), table_name='ab_user')
    op.drop_index(op.f('ix_ab_user_email'), table_name='ab_user')
    op.drop_table('ab_user')
    # ### end Alembic commands ###


